name: Develop CI

run-name: PR CI

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  godot-ci:
    uses: PeterChauYEG/labone-actions/.github/workflows/godot-pr.yml@main
    secrets: inherit
