name: Develop CI

run-name: PR CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]

jobs:
  ci:
    uses: PeterChauYEG/labone-actions/.github/workflows/mobile-pr.yml@main
    secrets: inherit
