name: Main CI

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: PeterChauYEG/labone-actions/.github/workflows/web-main.yml@main
    secrets: inherit
    with:
      dokku_remote_url: 'ssh://dokku@192.168.1.31:22/<app-name>'
