name: Node Main Orchestrator

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: '.'
      also_treat_actions_bot_as_dependabot:
        type: boolean
        required: false
        default: false
      dokku_remote_url:
        type: string
        required: true
      extra_deps_paths:
        type: string
        required: false
        default: ''
      extra_deps_cache_key_glob_1:
        type: string
        required: false
        default: ''
      extra_deps_cache_key_glob_2:
        type: string
        required: false
        default: ''
      test_script_args:
        type: string
        required: false
        default: '--cache --cacheDirectory .jestcache'
      security_scan_trivyignores:
        type: string
        required: false
        default: ''

permissions:
  contents: read

jobs:
  ci:
    name: ci
    uses: PeterChauYEG/labone-actions/.github/workflows/main-node-ci.yml@main
    secrets: inherit
    with:
      working-directory: ${{ inputs.working-directory }}
      is_dependabot: ${{ github.event.head_commit.author.username == 'dependabot[bot]' || (inputs.also_treat_actions_bot_as_dependabot && github.event.head_commit.author.username == 'github-actions[bot]') }}
      enable_build: true
      enable_test: true
      enable_deploy: true
      enable_slack_notification: true
      enable_security_scan: true
      security_scan_trivyignores: ${{ inputs.security_scan_trivyignores }}
      dokku_remote_url: ${{ inputs.dokku_remote_url }}
      extra_deps_paths: ${{ inputs.extra_deps_paths }}
      extra_deps_cache_key_glob_1: ${{ inputs.extra_deps_cache_key_glob_1 }}
      extra_deps_cache_key_glob_2: ${{ inputs.extra_deps_cache_key_glob_2 }}
      test_script_args: ${{ inputs.test_script_args }}
