name: Rust Service Main Orchestrator

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: '.'
      also_treat_actions_bot_as_dependabot:
        type: boolean
        required: false
        default: false
      pre_build_command:
        type: string
        required: false
        default: ''
      dokku_remote_url:
        type: string
        required: true

permissions:
  contents: read

jobs:
  ci:
    name: ci
    uses: PeterChauYEG/labone-actions/.github/workflows/main-rust-ci.yml@main
    secrets: inherit
    with:
      working-directory: ${{ inputs.working-directory }}
      is_dependabot: ${{ github.event.head_commit.author.name == 'dependabot[bot]' || (inputs.also_treat_actions_bot_as_dependabot && github.event.head_commit.author.name == 'github-actions[bot]') }}
      pre_build_command: ${{ inputs.pre_build_command }}
      enable_build: true
      enable_test: true
      enable_deploy: true
      enable_slack_notification: true
      dokku_remote_url: ${{ inputs.dokku_remote_url }}
