name: Web PR Orchestrator

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: '.'
      pr_base_sha:
        type: string
        required: false
        default: ''
      also_treat_actions_bot_as_dependabot:
        type: boolean
        required: false
        default: false
      extra_deps_paths:
        type: string
        required: false
        default: ''
      test_script_args:
        type: string
        required: false
        default: '--cache --cacheDirectory .jestcache'

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: ci
    if: github.event.action != 'closed'
    permissions:
      contents: read
      pull-requests: write
    uses: PeterChauYEG/labone-actions/.github/workflows/develop-ci.yml@main
    secrets: inherit
    with:
      working-directory: ${{ inputs.working-directory }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_base_sha: ${{ inputs.pr_base_sha }}
      is_dependabot: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || (inputs.also_treat_actions_bot_as_dependabot && github.event.pull_request.user.login == 'github-actions[bot]') }}
      enable_ls_lint: true
      enable_build: true
      enable_test: true
      enable_a11y: true
      enable_design_system: true
      enable_dead_code: true
      enable_duplicate_code: true
      enable_e2e: true
      enable_react_tech_debt: true
      enable_max_lines: true
      enable_tech_debt: true
      extra_deps_paths: ${{ inputs.extra_deps_paths }}
      test_script_args: ${{ inputs.test_script_args }}

  actionlint:
    if: github.event.action != 'closed'
    uses: PeterChauYEG/labone-actions/.github/workflows/actionlint.yml@main
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
